title: Qi Wang's Homepage
page-top-title: Qi(Austin) Wang
top-section-bg-text: Mathematics and Applied Mathematics
home-subtitle: Qi Wang&ensp;|&ensp;王淇
copyright-text: "&copy; Qi Wang 2024-2025. All Rights Reserved."
